config/routes.rb
Rails.application.routes.draw do
  resources :article_categories
  resources :categories
  resources :user_clips

  resources :articles do
    resources :comments
  end

  resources :clips, only: [:index, :show] do
    resources :opinions do
      resources :likes, :comments
    end

    collection do
      get 'search'
    end
  end

  devise_for :users
  root 'home#index'
  get 'home/index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :article_categories
  has_many :categories, through: :article_categories
  has_many :comments, as: :commentable

  require "date"
  def upcase_title
  	self.title = title.upcase
  	self.title = title +  " " + Date.today.to_s
  end

 def reading_time_predicition
  # 文字数を取得する
  text_count = body.size

  # 文字数を100（1分）で割って、この記事を読むのに何分かかるかをreading_time変数に入れる
  reading_time = text_count / 100

  # 0が返ってきたら1分以内、それ以上だったら〜分を返す
  reading_time == 0 ? "1分以内" : "約#{reading_time}分"
 end

  def self.find_tests
   Article.last
  end

end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories 
  has_many :articles, through: :article_categories
end

app/models/clip.rb
class Clip < ApplicationRecord
has_many :user_clips, dependent: :destroy
has_many :users, through: :user_clips

has_many :likes
has_many :opinions, dependent: :destroy
before_save :create_page #メソッド 呼び出し
  def create_page
    begin
      page = MetaInspector.new(url)
      self.title = page.title
      self.description = page.best_description
      self.image = page.images.best
    rescue => error
      errors.add(:base, "無効なURLです。")
      throw :abort
    end
  end

  def self.search(search)
  	return Clip.all unless search
    search ? where('CONCAT(title,description)  LIKE ?', "%#{search}%") : all
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :opinion
  belongs_to :clip
  belongs_to :user
end

app/models/opinion.rb
class Opinion < ApplicationRecord
  belongs_to :clip, counter_cache: true
  belongs_to :user
  has_many :comments, as: :commentable
  has_many :likes, dependent: :destroy
  validates :title, :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         # , :confirmable
  has_many :user_clips
  has_many :clips, through: :user_clips
  has_many :opinions, dependent: :destroy
  has_many :likes, dependent: :destroy
end

app/models/user_clip.rb
class UserClip < ApplicationRecord
  belongs_to :user
  belongs_to :clip, counter_cache: true
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]  
  # GET /articles
  # GET /articles.json
  def index
    require "api_helper"

    uri1 = URI.parse('https://newsapi.org/v2/top-headlines?country=us&apiKey=9f88e3748ec14d1a98204072a6aa8833')
    json1 = Net::HTTP.get(uri1)
    result_us = JSON.parse(json1)
    @articles = Article.new
    @articles = result_us['articles']
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  def search
    #Viewのformで取得したパラメータをモデルに渡す
    @articles = Article.all
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    post_text = params[:data][:text]
    results = { :message => post_text }
    render partial: 'ajax_partial', locals: { :results => results }
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :body, category_ids: [])
    end
end

app/controllers/clips_controller.rb
class ClipsController < ApplicationController
  before_action :set_clip, only: [:show, :edit, :update, :destroy, :opinion_show]

  # GET /clips
  # GET /clips.json
  def index
    @clips = Clip.all
  end

  # GET /clips/1
  # GET /clips/1.json
  def show
    @opinion = Opinion.new
    @clips = Clip.all.order(opinions_count: "desc").limit(8)
    @clip = Clip.find(params[:id])
  end

  # GET /clips/new
  def new
    @clip = Clip.new
  end

  # GET /clips/1/edit
  def edit
  end

  # POST /clips
  # POST /clips.json
  def create
    @clip = Clip.new(clip_params)

    respond_to do |format|
      if @clip.save
        format.html { redirect_to @clip, notice: 'Clip was successfully created.' }
        format.json { render :show, status: :created, location: @clip }
      else
        format.html { render :new }
        format.json { render json: @clip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clips/1
  # PATCH/PUT /clips/1.json
  def update
    respond_to do |format|
      if @clip.update(clip_params)
        format.html { redirect_to @clip, notice: 'Clip was successfully updated.' }
        format.json { render :show, status: :ok, location: @clip }
      else
        format.html { render :edit }
        format.json { render json: @clip.errors, status: :unprocessable_entity }
      end
    end
  end

  def search
    @clips = Clip.search(params[:search])
  end
  # DELETE /clips/1
  # DELETE /clips/1.json
  def destroy
    @clip.destroy
    respond_to do |format|
      format.html { redirect_to clips_url, notice: 'Clip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_clip
   @clip = Clip.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def clip_params
    params.require(:clip).permit(:url, :title, :description, :image)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
	 @clips = Clip.all
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_opinion, :set_clip

  def create
    @opinion = Opinion.find params[:opinion_id]
    @like = @opinion.likes.build(user: current_user)
    respond_to do |format|
      if @like.save
        format.html { redirect_to opinion_path(@like.opinion),
         notice: 'いいねを押しました' }
        format.js
      end
    end
  end

  def destroy
    @like = Like.find_by(user_id: current_user.id, opinion_id: @opinion.id, clip_id: @clip.id)
    @like.destroy
  end

  private
  def set_clip
    @clip = Clip.find(params[:clip_id])
  end

  def set_opinion
    @opinion = Opinion.find(params[:opinion_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/clips_helper.rb
module ClipsHelper
  def jp_date(date)
    date.strftime("%Y年%m月%d日 %H:%M")
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/opinions_helper.rb
module OpinionsHelper
end

app/helpers/user_clips_helper.rb
module UserClipsHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.collection_select :category_ids, Category.all, :id, :name %>
  </div>

  <br>
  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<div style = "text-align: center;"><input type="button" value="最新の記事に更新" onclick="window.location.reload();" class="btn btn-danger"></div>
<h4>トピックス</h4>
<div class="card-groups" style ="background-color: black;">
<% @articles.each do |article| %>
<div class="card">
  <div class="row no-gutters">
    <div class="col-md-4" style = "max-height: 250px;">
      <img src="<%= article["urlToImage"] %>" class="card-img" alt="news-image" style = "height:100%;">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title"><%= article["title"] %></h5>
        <%= article["publishedAt"].in_time_zone('Tokyo').strftime('%Y/%m/%d %H:%M')%> post<br><br>
        <p><%= truncate(article["description"] , length:100) %>
        <br><br><a class="btn btn-primary" href="<%= article["url"]  %>" target="_blank">記事の続きを読む</a>
        </p>
      </div>
    </div>
  </div>
</div>
<% end %>
</div>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.upcase_title %>
</p>

<p>
    <strong>Body:</strong>
    <%= @article.body %>
</p>

<p>
    <strong>Category:</strong>
    <% @article.article_categories.each do |article_categories| %>
     <%= article_categories.category.name %>
    <% end %>
</p>

<p>
  <strong>読了予想時間：</strong>
    <%= @article.reading_time_predicition %>分
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/clips/_form.html.erb
<%= form_with(model: clip, local: true) do |form| %>
  <% if clip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(clip.errors.count, "error") %> prohibited this clip from being saved:</h2>

      <ul>
      <% clip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clips/edit.html.erb
<h1>Editing Clip</h1>

<%= render 'form', clip: @clip %>

<%= link_to 'Show', @clip %> |
<%= link_to 'Back', home_index_path %>

app/views/clips/index.html.erb
<h4>ユーザークリップ<%= form_tag(search_clips_path,:method => 'get', class: "btn btn-outline-light btn-lg") do %>
  <%= text_field_tag :search %>
  <%= submit_tag '検索', :name => nil %></h4>
<% end %>
<div class="card-groups">
<% @clips.each do |clip| %>
<div class="card">
  <div class="row no-gutters">
    <div class="col-md-4" style = "max-height: 250px;">
      <img src="<%= clip.image %>" class="card-img" alt="news-image" style = "height:100%;">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h4 class="card-title"><%= clip.title %><a><%= clip["publishedAt"] %></a></h4>
        <p><%= truncate(clip["description"] , length:100) %></p>
        <p><%= fa_icon 'bookmark 2x', style: "color: orange" %>
        <%= clip.user_clips_count %>クリップ
        <%= fa_icon 'users 2x', style: "color: orange" %>
        <%= clip.opinions_count %>オピニオン
        <br><br><%= link_to 'オピニオン一覧', clip, class: "btn btn-primary", data: {"turbolinks" => false}%>
        </p>
      </div>
    </div>
  </div>
</div>
<% end %>
</div>

app/views/clips/new.html.erb
<h1>New Clip</h1>

<%= render 'form', clip: @clip %>

<%= link_to 'Back', clips_path %>

app/views/clips/search.html.erb
<div class="card-groups">
<% @clips.each do |clip| %>
<div class="card">
  <div class="row no-gutters">
    <div class="col-md-4" style = "max-height: 250px;">
      <img src="<%= clip.image %>" class="card-img" alt="news-image" style = "height:100%;">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h4 class="card-title"><%= clip.title %><a><%= clip["publishedAt"] %></a></h4>
        <p style = "font-size:20px"><%= truncate(clip["description"] , length:100) %>
        <br><br><%= link_to 'オピニオンを見る', clip, class: "btn btn-primary"%>
        </p>
      </div>
    </div>
  </div>
</div>
<% end %>
</div>

app/views/clips/show.html.erb
<div class="row">
  <div class="col-md-8">
<ol class="breadcrumb mt-4">
  <li class="breadcrumb-item">
    <%= link_to "クリップ一覧", clips_url %></li>
  <li class="breadcrumb-item">
    <%= link_to @clip.title.truncate(25), @clip %></li>
</ol>
<div class="row">
  <h1><%= @clip.title %></h1>
  <div class="col-md-4">
    <%= image_tag @clip.image,class: 'img-fluid' if @clip.image %>
  </div>
  <div class="col-md-8">
    <%=link_to @clip.url, @clip.url,target: '_blank' %>
    <p><%= truncate(@clip["description"] , length:50) %></p>
    <%= fa_icon 'bookmark 2x', style: "color: orange" %>
    <%= @clip.user_clips_count %>クリップ
    <%= fa_icon 'users 2x', style: "color: orange" %>
    <%= @clip.opinions_count %>オピニオン
  </div>
  <div class="col-md-4">
  </div>
</div>
<h4>オピニオンする</h4>
<div class="opinion-form">
  <% if @opinion && @opinion.errors.any? %>
    <div id="error_explanation">
      <h5>
       <%= pluralize(@opinion.errors.count, "error") %>
      </h5>
      <ul>
      <% @opinion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_for [@clip, @opinion] do |f| %>
    <%= f.text_field :title, class: 'form-control my-2',  placeholder: 'オピニオンタイトルを書く' %>
    <%= f.text_area :body, class: 'form-control', placeholder: 'オピニオン本文を書く' %>
    <%= f.submit "オピニオン作成", class: 'btn btn-primary my-2' %>
  <% end %>
</div>
<h4>この記事に関するオピニオン</h4>
<% @clip.opinions.each do |opinion| %>
<div class="row">
  <div class="col-md-8">
  <h5><%= opinion.title %></h5>
  <%= opinion.user.email if opinion.user %>
  <%= simple_format @opinion.body %>
  <%= link_to  "続きを読む" ,clip_opinion_path(@clip) %>
  <div class="text-right small">
    <span class="text-muted">
       <%= jp_date opinion.created_at %>
    </span>
  </div>
  </div>
  <div class="col-md-4">
  </div>
</div>
<% end %>
</div>
  <div class="col-md-4">
    <h4>人気のオピニオン</h4>
    <% @clips.each do |clips| %>
    <li><%= link_to clips.title.truncate(25), clips %>
    <%=link_to clips.url, clips.url,target: '_blank' %>
    <p><%= truncate(clips["description"] , length:50) %></p>
    <%= fa_icon 'bookmark 2x', style: "color: orange" %>
    <%= clips.user_clips_count %>クリップ
    <%= fa_icon 'users 2x', style: "color: orange" %>
    <%= clips.opinions_count %>オピニオン
    </li>
    <% end %>
  </div>
</div>

app/views/likes/_like.html.erb
<% if Like.find_by(user_id: current_user.id, opinion_id: opinion.id, clip_id: @clip.id)%>
  <%= link_to clip_opinion_likes_path(@clip, opinion),{ method: :delete, class: "heart-link", remote: true} do %>
    <i class="material-icons" id="favorite_icon">favorite</i>いいね
  <% end %>
<% else %>
  <%= link_to clip_opinion_like_path(@clip, opinion),{ method: :post, class: "heart-link", remote: true} do %>
    <i class="material-icons">favorite_border</i>いいね
  <% end %>
<% end %>
<%= opinion.likes.length %>

app/views/likes/create.js.erb
(".like").html("<%= j render 'opinions/like' %>")

app/views/likes/destroy.js.erb
$("#like-<%= @opinion.id %>").html('<%= j(render partial: 'likes/like', locals:{ opinion: @opinion }) %>'); 