config/routes.rb
Rails.application.routes.draw do
  resources :article_categories
  resources :categories
  resources :user_clips

  resources :articles do
    resources :comments
  end

  resources :clips, only: [:index, :show] do
    resources :opinions do
      resources :likes, :comments
    end

    collection do
      get 'search'
    end
  end

  devise_for :users
  root 'home#index'
  get 'home/index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :article_categories
  has_many :categories, through: :article_categories
  has_many :comments, as: :commentable

  require "date"
  def upcase_title
  	self.title = title.upcase
  	self.title = title +  " " + Date.today.to_s
  end

 def reading_time_predicition
  # 文字数を取得する
  text_count = body.size

  # 文字数を100（1分）で割って、この記事を読むのに何分かかるかをreading_time変数に入れる
  reading_time = text_count / 100

  # 0が返ってきたら1分以内、それ以上だったら〜分を返す
  reading_time == 0 ? "1分以内" : "約#{reading_time}分"
 end

  def self.find_tests
   Article.last
  end

end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories 
  has_many :articles, through: :article_categories
end

app/models/clip.rb
class Clip < ApplicationRecord
has_many :user_clips, dependent: :destroy
has_many :users, through: :user_clips

has_many :likes
has_many :opinions, dependent: :destroy
before_save :create_page #メソッド 呼び出し
  def create_page
    begin
      page = MetaInspector.new(url)
      self.title = page.title
      self.description = page.best_description
      self.image = page.images.best
    rescue => error
      errors.add(:base, "無効なURLです。")
      throw :abort
    end
  end

  def self.search(search)
  	return Clip.all unless search
    search ? where('CONCAT(title,description)  LIKE ?', "%#{search}%") : all
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :opinion
  belongs_to :clip
  belongs_to :user
end

app/models/opinion.rb
class Opinion < ApplicationRecord
  belongs_to :clip, counter_cache: true
  belongs_to :user
  has_many :comments, as: :commentable
  has_many :likes, dependent: :destroy
  validates :title, :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         # , :confirmable
  has_many :user_clips
  has_many :clips, through: :user_clips
  has_many :opinions, dependent: :destroy
  has_many :likes, dependent: :destroy
end

app/models/user_clip.rb
class UserClip < ApplicationRecord
  belongs_to :user
  belongs_to :clip, counter_cache: true
end

app/controllers/article_categories_controller.rb
class ArticleCategoriesController < ApplicationController
  before_action :set_article_category, only: [:show, :edit, :update, :destroy]

  # GET /article_categories
  # GET /article_categories.json
  def index
    @article_categories = ArticleCategory.all
  end

  # GET /article_categories/1
  # GET /article_categories/1.json
  def show
  end

  # GET /article_categories/new
  def new
    @article_category = ArticleCategory.new
  end

  # GET /article_categories/1/edit
  def edit
  end

  # POST /article_categories
  # POST /article_categories.json
  def create
    @article_category = ArticleCategory.new(article_category_params)

    respond_to do |format|
      if @article_category.save
        format.html { redirect_to @article_category, notice: 'Article category was successfully created.' }
        format.json { render :show, status: :created, location: @article_category }
      else
        format.html { render :new }
        format.json { render json: @article_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /article_categories/1
  # PATCH/PUT /article_categories/1.json
  def update
    respond_to do |format|
      if @article_category.update(article_category_params)
        format.html { redirect_to @article_category, notice: 'Article category was successfully updated.' }
        format.json { render :show, status: :ok, location: @article_category }
      else
        format.html { render :edit }
        format.json { render json: @article_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /article_categories/1
  # DELETE /article_categories/1.json
  def destroy
    @article_category.destroy
    respond_to do |format|
      format.html { redirect_to article_categories_url, notice: 'Article category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article_category
      @article_category = ArticleCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_category_params
      params.require(:article_category).permit(:article_id, :category_id)
    end
end

app/controllers/clips_controller.rb
class ClipsController < ApplicationController
  before_action :set_clip, only: [:show, :edit, :update, :destroy, :opinion_show]

  # GET /clips
  # GET /clips.json
  def index
    @clips = Clip.all
  end

  # GET /clips/1
  # GET /clips/1.json
  def show
    @opinion = Opinion.new
    @clips = Clip.all.order(opinions_count: "desc").limit(8)
    @clip = Clip.find(params[:id])
  end

  # GET /clips/new
  def new
    @clip = Clip.new
  end

  # GET /clips/1/edit
  def edit
  end

  # POST /clips
  # POST /clips.json
  def create
    @clip = Clip.new(clip_params)

    respond_to do |format|
      if @clip.save
        format.html { redirect_to @clip, notice: 'Clip was successfully created.' }
        format.json { render :show, status: :created, location: @clip }
      else
        format.html { render :new }
        format.json { render json: @clip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clips/1
  # PATCH/PUT /clips/1.json
  def update
    respond_to do |format|
      if @clip.update(clip_params)
        format.html { redirect_to @clip, notice: 'Clip was successfully updated.' }
        format.json { render :show, status: :ok, location: @clip }
      else
        format.html { render :edit }
        format.json { render json: @clip.errors, status: :unprocessable_entity }
      end
    end
  end

  def search
    @clips = Clip.search(params[:search])
  end
  # DELETE /clips/1
  # DELETE /clips/1.json
  def destroy
    @clip.destroy
    respond_to do |format|
      format.html { redirect_to clips_url, notice: 'Clip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_clip
   @clip = Clip.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def clip_params
    params.require(:clip).permit(:url, :title, :description, :image)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
	 @clips = Clip.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_categories_helper.rb
module ArticleCategoriesHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/clips_helper.rb
module ClipsHelper
  def jp_date(date)
    date.strftime("%Y年%m月%d日 %H:%M")
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/opinions_helper.rb
module OpinionsHelper
end

app/helpers/user_clips_helper.rb
module UserClipsHelper
end

app/views/article_categories/_form.html.erb
<%= form_with(model: article_category, local: true) do |form| %>
  <% if article_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article_category.errors.count, "error") %> prohibited this article_category from being saved:</h2>

      <ul>
      <% article_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :article_id %>
    <%= form.text_field :article_id %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.text_field :category_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/article_categories/edit.html.erb
<h1>Editing Article Category</h1>

<%= render 'form', article_category: @article_category %>

<%= link_to 'Show', @article_category %> |
<%= link_to 'Back', article_categories_path %>

app/views/article_categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Article Categories</h1>

<table>
  <thead>
    <tr>
      <th>Article</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @article_categories.each do |article_category| %>
      <tr>
        <td><%= article_category.article %></td>
        <td><%= article_category.category %></td>
        <td><%= link_to 'Show', article_category %></td>
        <td><%= link_to 'Edit', edit_article_category_path(article_category) %></td>
        <td><%= link_to 'Destroy', article_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article Category', new_article_category_path %>

app/views/article_categories/new.html.erb
<h1>New Article Category</h1>

<%= render 'form', article_category: @article_category %>

<%= link_to 'Back', article_categories_path %>

app/views/article_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Article:</strong>
  <%= @article_category.article %>
</p>

<p>
  <strong>Category:</strong>
  <%= @article_category.category %>
</p>

<%= link_to 'Edit', edit_article_category_path(@article_category) %> |
<%= link_to 'Back', article_categories_path %>