config/routes.rb
Rails.application.routes.draw do
  resources :article_categories
  resources :categories
  resources :user_clips

  resources :articles do
    resources :comments
  end

  resources :clips, only: [:index, :show] do
    resources :opinions do
      resources :likes, :comments
    end

    collection do
      get 'search'
    end
  end

  devise_for :users
  root 'home#index'
  get 'home/index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :article_categories
  has_many :categories, through: :article_categories
  has_many :comments, as: :commentable

  require "date"
  def upcase_title
  	self.title = title.upcase
  	self.title = title +  " " + Date.today.to_s
  end

 def reading_time_predicition
  # 文字数を取得する
  text_count = body.size

  # 文字数を100（1分）で割って、この記事を読むのに何分かかるかをreading_time変数に入れる
  reading_time = text_count / 100

  # 0が返ってきたら1分以内、それ以上だったら〜分を返す
  reading_time == 0 ? "1分以内" : "約#{reading_time}分"
 end

  def self.find_tests
   Article.last
  end

end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories 
  has_many :articles, through: :article_categories
end

app/models/clip.rb
class Clip < ApplicationRecord
has_many :user_clips, dependent: :destroy
has_many :users, through: :user_clips

has_many :likes
has_many :opinions, dependent: :destroy
before_save :create_page #メソッド 呼び出し
  def create_page
    begin
      page = MetaInspector.new(url)
      self.title = page.title
      self.description = page.best_description
      self.image = page.images.best
    rescue => error
      errors.add(:base, "無効なURLです。")
      throw :abort
    end
  end

  def self.search(search)
  	return Clip.all unless search
    search ? where('CONCAT(title,description)  LIKE ?', "%#{search}%") : all
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :opinion
  belongs_to :clip
  belongs_to :user
end

app/models/opinion.rb
class Opinion < ApplicationRecord
  belongs_to :clip, counter_cache: true
  belongs_to :user
  has_many :comments, as: :commentable
  has_many :likes, dependent: :destroy
  validates :title, :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         # , :confirmable
  has_many :user_clips
  has_many :clips, through: :user_clips
  has_many :opinions, dependent: :destroy
  has_many :likes, dependent: :destroy
end

app/models/user_clip.rb
class UserClip < ApplicationRecord
  belongs_to :user
  belongs_to :clip, counter_cache: true
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
	 @clips = Clip.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/clips_helper.rb
module ClipsHelper
  def jp_date(date)
    date.strftime("%Y年%m月%d日 %H:%M")
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/opinions_helper.rb
module OpinionsHelper
end

app/helpers/user_clips_helper.rb
module UserClipsHelper
end

app/views/categoys/_form.html.erb
<%= form_with(model: categoy, local: true) do |form| %>
  <% if categoy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(categoy.errors.count, "error") %> prohibited this categoy from being saved:</h2>

      <ul>
      <% categoy.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categoys/edit.html.erb
<h1>Editing Categoy</h1>

<%= render 'form', categoy: @categoy %>

<%= link_to 'Show', @categoy %> |
<%= link_to 'Back', categoys_path %>

app/views/categoys/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categoys</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categoys.each do |categoy| %>
      <tr>
        <td><%= categoy.name %></td>
        <td><%= link_to 'Show', categoy %></td>
        <td><%= link_to 'Edit', edit_categoy_path(categoy) %></td>
        <td><%= link_to 'Destroy', categoy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Categoy', new_categoy_path %>

app/views/categoys/new.html.erb
<h1>New Categoy</h1>

<%= render 'form', categoy: @categoy %>

<%= link_to 'Back', categoys_path %>

app/views/categoys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @categoy.name %>
</p>

<%= link_to 'Edit', edit_categoy_path(@categoy) %> |
<%= link_to 'Back', categoys_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>News Ink</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5d3c52cf7c2a16f6"></script>
    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <script src='js/bootstrap.js'></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script>
      (adsbygoogle = window.adsbygoogle || []).push({
        google_ad_client: "ca-pub-18100103632046477529",
        enable_page_level_ads: true
      });
      // ページをreloadする方法
    </script>
    <script>
      window.onunload = function(){location.reload();}
    </script>
    <script>(function(t,a,y,o,r,i){r=a.createElement(y),i=a.getElementsByTagName(y)[0];r.type='text/javascript';r.async=1;r.src='http://tayori.com/form/64410234d28d9e9b166d7579922566c0736431cb/tag.js';r.id='tayori-tag';i.parentNode.insertBefore(r,i)})(window,document,'script');
    </script>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-144911894-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', 'UA-144911894-1');
    </script>
    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <link href="style.css" rel="stylesheet" type="text/css" media="(min-width: 960px) and (max-width: 1279px)" >
  </head>
    <% if current_page?(root_path) %>
    <div class="jumbotron text-center hero">
    <div class="container">
       <h1>News Ink</h1>
       <p>News Inkはニュースを共有するための<br>プラットフォームです</p>
    </div>
    </div>
    <% end %>
  <body onLoad="rCheck()">
     <nav class="navbar navbar-expand-lg navbar-dark bg-danger">
      <a class="navbar-brand" href="/" data-turbolinks="false" >News Ink</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation" style =  "text-align:left;">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav"  style = "color:white;">
        <ul class="navbar-nav">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "トピックス", articles_path, method: :get,:style=>"color:white;padding-left:10px;", data: {"turbolinks" => false} %>
            </li>
            <li class="nav-item">
              <%= link_to "ユーザークリップ", clips_path, method: :get,:style=>"color:white;padding-left:10px;" , data: {"turbolinks" => false} %>
            </li>
            <li class="nav-item">
              <%= link_to "マイクリップ", user_clips_path, method: :get,:style=>"color:white;padding-left:10px;" , data: {"turbolinks" => false} %>
            </li>
            <li class="nav-item">
              <span style = "color:white;padding-left:10px;"><%= current_user.email %></span>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete,:style=>"color:white;padding-left:10px;" , data: {"turbolinks" => false} %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "ログイン", new_user_session_path,:style=>"color:white;padding-left:10px;"  , data: {"turbolinks" => false} %>
            </li>
          <% end %>
        </ul>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <%= link_to "新規クリップ", new_user_clip_path, class: 'btn btn-outline-light' %>
          </li>
        </ul>
      </div>
    </nav>
    <% if notice || alert %>
      <div class="alert alert-warning">
        <div class="container">
          <%= notice %>
          <%= alert %>
          <button type="button" class="close" 
        data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      </div>
    <% end %>
    <div class="addthis_inline_share_toolbox_nenf"  style = "text-align:center;padding-top: 30px;"></div>
    <div class="container content" style = "width: 100%;padding-top: 100px;">
     <%= yield %>
    </div>
    </body>
    <div class="addthis_inline_share_toolbox_nenf" style = "text-align:center;padding-bottom: 100px;"></div>
    <div class="footer">
      <div class="container">
        <ul style = "list-style: none;">
          <li>© Copyright 2019 All Rights Reserved</li>
          <li>お問い合わせ</li>
          <li>プライバシーポリシー</li>
          <li>ヘルプ</li>
        </ul>
      </div>
</html>